.PHONY: clean All

All:
	@echo "----------Building project:[ esercizi19102017 - Debug ]----------"
	@cd "esercizi19102017" && "$(MAKE)" -f  "esercizi19102017.mk"
clean:
	@echo "----------Cleaning project:[ esercizi19102017 - Debug ]----------"
	@cd "esercizi19102017" && "$(MAKE)" -f  "esercizi19102017.mk" clean
