.PHONY: clean All

All:
	@echo "----------Building project:[ recor_selection_sort - Debug ]----------"
	@cd "recor_selection_sort" && "$(MAKE)" -f  "recor_selection_sort.mk"
clean:
	@echo "----------Cleaning project:[ recor_selection_sort - Debug ]----------"
	@cd "recor_selection_sort" && "$(MAKE)" -f  "recor_selection_sort.mk" clean
