.PHONY: clean All

All:
	@echo "----------Building project:[ lista-tramite-oggetti-es-1-11 - Debug ]----------"
	@cd "lista-tramite-oggetti-es-1-11" && "$(MAKE)" -f  "lista-tramite-oggetti-es-1-11.mk"
clean:
	@echo "----------Cleaning project:[ lista-tramite-oggetti-es-1-11 - Debug ]----------"
	@cd "lista-tramite-oggetti-es-1-11" && "$(MAKE)" -f  "lista-tramite-oggetti-es-1-11.mk" clean
